# -*- coding: utf-8 -*-
"""assignment day 6 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vxnRPR1rJAiCcFUhvtyaT6JywdYFbYW-
"""

def mod_div(fun):
	def deno(a, b):
		if a < b :
			a, b = b, a
		return fun(a, b)
	return deno
	
@mod_div
def div(a, b):
	return  a // b

a, b = (int(i) for i in input("Enter two Nunbers: ").split())


print(div(a, b))