# -*- coding: utf-8 -*-
"""Assignment Day 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UiQBIDguUMUmhu3gzrOplBYeIY14aDW0
"""

num1 = input('Enter first number: ')
num2 = input('Enter second number: ')

# Add two numbers
sum = float(num1) + float(num2)

# Display the sum
print('The sum of {0} and {1} is {2}'.format(num1, num2, sum))





x = [int(i) for i in input('Enter multiple values : ').split()]

sum = 0
for j in x:
  sum += j

print(sum)





a = int(input('Enter first no :'))
b = int(input('Enter second no :'))
c = int(input('Enter Third no :'))
d = int(input('Enter another no :'))
print ('Sum',a + b + c + d )