# -*- coding: utf-8 -*-
"""assignment day 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rrF7wkqMP-l_-tOs7e9lPu8B1-WYA8ua
"""

John = list(range(1,50))
  
result3 = list(filter(lambda x: (x % 3 == 0), John)) 
result5 = list(filter(lambda x: (x % 5 == 0), John)) 
  
print("This number only divisible by 3  : \n",result3) 
print("This number only divisible by 5  : ",result5)