# -*- coding: utf-8 -*-
"""assignment day 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O9PwpiVxOJVQtOtCRNMdV9dFJyG1r_MO
"""

Ages = {'Raj':30, 'Priya':25, 'John':35, 'Michael':44, 'Chloe':32, 'Linda':40}

max_value = max(Ages.values())
print(max_value)

max_key = max(Ages, key=Ages.get)
print(max_key)